apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: web
spec:
  minReadySeconds: 10
  paused: false
  progressDeadlineSeconds: 60
  replicas: 10
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      layer: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      name: frontend-app
      namespace: web
    spec:
      containers:
      - name: webserver
        image: nginx
        imagePullPolicy: IfNotPresent