apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: hello-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-service
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-service
    spec:
      containers:
        - image: 552740142516.dkr.ecr.eu-west-1.amazonaws.com/hello-service-repo:latest
          imagePullPolicy: Always
          name: hello-service
          ports:
            - containerPort: 80
          env:
            - name: HELLO
              value: Hello
        - image: datadog/agent
          resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          name: datadog-agent
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-api-key
                  key: datadog-api-key
            - name: DD_SITE
              value: "datadoghq.eu"
            - name: DD_EKS_FARGATE
              value: "true"
            - name: DD_CLUSTER_NAME
              value: "productioneutriangleE9CAFAB5-e56545dcf59e4914b4e7b87daeb86176"
            - name: DD_KUBERNETES_KUBELET_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
