const addressFormats = {
  'UNITED KINGDOM': [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['locality'],
    ['region'],
    ['postcode'],
    ['country'],
  ],
  ITALY: [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['postcode', 'locality', 'region'],
    ['country'],
  ],
  FRANCE: [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['locality'],
    ['postcode', 'region'],
    ['country'],
  ],
  USA: [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['locality', 'region', 'postcode'],
    ['country'],
  ],
  GERMANY: [
    ['honorific'],
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['postcode', 'region'],
    ['country'],
  ],
  SWITZERLAND: [
    ['honorific'],
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['postcode', 'region'],
    ['country'],
  ],
  'HONG KONG': [
    ['honorific', 'recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['region'],
    ['country'],
  ],

  JAPAN: [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['locality', 'region', 'postcode'],
  ],
  POLAND: [
    ['recipient'],
    ['addressLine1'],
    ['addressLine2'],
    ['addressLine3'],
    ['addressLine4'],
    ['postcode', 'locality'],
    ['country'],
  ],
};

module.exports = addressFormats;
