const LOGIN_USER = "LOGIN_USER";
const IS_LOGGED_IN = "IS_LOGGED_IN";
const SIGNOUT_USER = "SIGNOUT_USER";
const CREATE_DRAFT = "CREATE_DRAFT";
const UPDATE_DRAFT_LOCATION = "UPDATE_DRAFT_LOCATION";
const DELETE_DRAFT = "DELETE_DRAFT";
const GET_PINS = "GET_PINS";
const CREATE_PIN = "CREATE_PIN";
const SET_PIN = "SET_PIN";
const DELETE_PIN = "DELETE_PIN";
const CREATE_COMMENT = "CREATE_COMMENT";

export {
  LOGIN_USER,
  IS_LOGGED_IN,
  SIGNOUT_USER,
  CREATE_DRAFT,
  UPDATE_DRAFT_LOCATION,
  DELETE_DRAFT,
  GET_PINS,
  CREATE_PIN,
  SET_PIN,
  DELETE_PIN,
  CREATE_COMMENT,
};
