apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: busybox
      command: ["sh", "-c", "echo hello world"]
  initContainers:
    - name: my-init-container
      image: busybox
      command:
        [
          "sh",
          "git clone https://github.com/mattlongcode/learning.git && learning/run-init.sh; done;",
        ]
