const MAXIMUM_SEARCH_RESULTS = 6;
const MINIMUM_SEARCH_TERM_LENGTH = 2;
const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
const UPDATE_SEARCH_RESULTS_COUNT = "UPDATE_SEARCH_RESULTS_COUNT";
const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
const SET_LOADING = "SET_LOADING";
const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

export {
  MAXIMUM_SEARCH_RESULTS,
  MINIMUM_SEARCH_TERM_LENGTH,
  UPDATE_SEARCH_TERM,
  UPDATE_SEARCH_RESULTS,
  UPDATE_SEARCH_RESULTS_COUNT,
  CLEAR_SEARCH_RESULTS,
  SET_LOADING,
  SET_ERROR_MESSAGE,
  CLEAR_ERROR_MESSAGE
};
