const addressCases = [
  {
    country: 'UNITED KINGDOM',
    format: {
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: true },
      region: { upper: true },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'ITALY',
    format: {
      recipient: { upper: true },
      addressLine1: { upper: true },
      addressLine2: { upper: true },
      addressLine3: { upper: true },
      addressLine4: { upper: true },
      locality: { upper: true },
      region: { upper: true },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'FRANCE',
    format: {
      recipient: { upper: false },
      addressLine1: { upper: true },
      addressLine2: { upper: true },
      addressLine3: { upper: true },
      addressLine4: { upper: true },
      locality: { upper: true },
      region: { upper: true },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'USA',
    format: {
      recipient: { upper: true },
      addressLine1: { upper: true },
      addressLine2: { upper: true },
      addressLine3: { upper: true },
      addressLine4: { upper: true },
      locality: { upper: true },
      region: { upper: true },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'GERMANY',
    format: {
      honorific: { upper: false },
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: false },
      region: { upper: false },
      postcode: { upper: false },
      country: { upper: true },
    },
  },
  {
    country: 'SWITZERLAND',
    format: {
      honorific: { upper: false },
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: false },
      region: { upper: false },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'HONG KONG',
    format: {
      honorific: { upper: false },
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: false },
      region: { upper: true },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'JAPAN',
    format: {
      honorific: { upper: false },
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: false },
      region: { upper: false },
      postcode: { upper: true },
      country: { upper: true },
    },
  },
  {
    country: 'POLAND',
    format: {
      honorific: { upper: false },
      recipient: { upper: false },
      addressLine1: { upper: false },
      addressLine2: { upper: false },
      addressLine3: { upper: false },
      addressLine4: { upper: false },
      locality: { upper: true },
      region: { upper: false },
      postcode: { upper: false },
      country: { upper: true },
    },
  },
];

module.exports = addressCases;
